services:
    app:
        image: book-vault:${APP_TAG:-latest}
        ports:
            - '80:80'
        env_file:
            - .env
        volumes:
            - db_data:/app/database
        depends_on:
            - meilisearch
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        environment:
            MEILI_NO_ANALYTICS: 'true'
            MEILI_MASTER_KEY: '${MEILISEARCH_KEY}'
        volumes:
            - 'meili_data:/meili_data'
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s

volumes:
    db_data:
    meili_data:
        driver: local
